### ISSUE TITLE
[REVIEW] Specify meaning for x and y when defining the grid

### ISSUE THREAD

**Issue by santisoler** [brmather/pycurious#15]
Part of https://github.com/openjournals/joss-reviews/issues/1544.

On `CurieGrid` docstring, would be nice to specify what `x` and `y` stands for.
Some users may be used to packages that uses `y` for easting and `x` for northing, while others may refer to a classical Cartesian axes, where `x` is usually assigned to the horizontal (easting) coordinate and `y` to the vertical one (northing).

Also, would be nice to specify the expected shape of the `grid` 2d-array: `(ny, nx)`.

**Comment by brmather** [comment]
Yes, I think it should be made as clear as possible that eastings and northings should be used (not longitude / latitude!) I have updated the docstring for `CurieGrid` in 27c40d5cd2685123c5d416d860220b248a86ba5d to elaborate that `x` and `y` are eastings and northings in metres. Also I've listed all the attributes available under the `CurieGrid` object. Thanks!
