### ISSUE TITLE
[REVIEW] Avoid repeating code

### ISSUE THREAD

**Issue by santisoler** [brmather/pycurious#19]
Part of https://github.com/openjournals/joss-reviews/issues/1544.

Methods `CurieGrid.radial_spectrum`, `CurieGrid.radial_spectrum_log` and `CurieGrid.azimuthal_spectrum` perform almost the same task. They differ only on a few lines. It's a good practice to avoid repeating code. It makes maintenance and testing a lot easier.

Would you consider creating a private method for `CurieGrid` that performs common tasks for these three methods, and refactor them to just call this new private method?

**Comment by brmather** [comment]
I've implemented two private methods for `CurieGrid` in cff769036d73905629a448812853614afda611b3:

1. `_taper_spectrum` prepares the taper array and bins for computing the power spectrum
2. `_FFT_spectrum` computes the radial power spectrum using a multiplication constant that is the only different between `radial_spectrum` and `radial_spectrum_log` (see #20 for more discussion).

I'm going to close this issue, but lets continue this discussion in #20
