### ISSUE TITLE
radial power spectrum

### ISSUE THREAD

**Issue by zhongpenggeo** [brmather/pycurious#3]
hello, I have a question about your code to compute radially averaged power spectrum.
In grid/curie.py, you compute power spectrum in function _radial_spectrum_ 

`FT = np.abs(np.fft.fft2(data*vtaper))`

But as I known, it shoud be `FT = np.abs(np.fft.fft2(data*vtaper))**2`, the square of absolute of fft, isn't it?

**Comment by brmather** [comment]
Thanks for your query. Could you provide a reference for that? To my knowledge the square is used simply to make all values in the power spectrum positive, which is accomplished with `np.abs`.

Could you provide more context, please?

**Comment by zhongpenggeo** [comment]
It's different in fatiando,
https://github.com/fatiando/fatiando/blob/ac2afbcb2d99b18f145cc1ed40075beb5f92dd5a/fatiando/gravmag/transform.py#L542

> Thanks for your query. Could you provide a reference for that? To my knowledge the square is used simply to make all values in the power spectrum positive, which is accomplished with `np.abs`.
> 
> Could you provide more context, please?

https://github.com/fatiando/fatiando/blob/ac2afbcb2d99b18f145cc1ed40075beb5f92dd5a/fatiando/gravmag/transform.py#L542
I find Power Density Spectra in Fatinado is square. And  you use`  rr = 2.0*np.log(FT[mask])` to compute log of Power Density Spectra in function 'radial_spectrum' in pycurious-src/pycurious/grid/curie.py , which is the same as log((FT)**2)

**Comment by brmather** [comment]
Sure, so it follows then there is no difference in the radial power spectrum. These statements return the same results:

1. `2*np.log(np.abs(np.fft.fft2(data*vtaper)))`
2. `np.log(np.abs(np.fft.fft2(data*vtaper))**2)`

Statement 1 is slightly more computationally friendly.
