### ISSUE TITLE
Some comments on pycurious

### ISSUE THREAD

**Issue by santisoler** [brmather/pycurious#5]
Nice package you have here! I didn't know it. I wrote some messy code for Curie Depth Point calculation when I was undergraduate, but it's old dated, not well written nor documented (my first baby steps on Python).
It implements the Tanaka method and a new I've been experimenting with: fitting the hole exponential curve with a Levenberg-Marquardt algorithm.
Besides I wrote an ugly GUI to manually select windows and seeing radial averaged power spectrum live.
I think I haven't uploaded the final version, but if you are interested I can do it.

Nevermind, your package looks really good!
I'll recommend yours if someone ask me to compute CDP!

**Comment by brmather** [comment]
Thanks! I started getting interest in CPD a couple of years ago. The motivation for `pycurious` was to cast CPD estimation within a Bayesian framework, which works quite well for the Bouligand *et al.* (2009) method. My colleague, @rdelhaye, added the Tanaka method to allow for a comparison between the two methods. Your curve-fitting approach sounds similar to the former - do you have more information on that?

A great many things have taken all of my time away from this project, but someday I would like to submit `pycurious` to JOSS - perhaps you would like to review it!? :smiley:

**Comment by santisoler** [comment]
I'm glad you had a good experience with Bouligand et al. (2009) method. I'm not familiar with it, but I don't quite like Tanaka method for a number of reasons. That's why I was interested on fitting the full curve instead of splitting it into low and high frequencies approximations (which lead to a linear fitting obtaining the top and bottom of the slab).
I was inspired by [Ross et al. (2006)](https://doi.org/10.1190/1.2335572) on fitting the hole curve.

Unfortunately I only described my research on my degree Thesis, which is in Spanish due to requirements of the Faculty. I uploaded it with a (very embarrassing now that I see it :persevere:) simple script to implement it - with an ugly GUI - to [santisoler/tesina-fisica](https://github.com/santisoler/tesina-fisica).
Fitting the hole curve helps to reject power spectrums that not fit into the hypothesis of random magnetization, which are often processed under Tanaka method because it has no meaningful tool to test whether it's good or not.
This makes finding the right window quite annoying because you could get a lot of rejected windows.


> A great many things have taken all of my time away from this project, but someday I would like to submit `pycurious` to JOSS - perhaps you would like to review it!? smiley

Yes! No problem! I can surely review `pycurious` if you want to submit it to JOSS.
I think that review will be very quick taking into account you already have experience on submitting a paper to JOSS.

**Comment by brmather** [comment]
> I'm glad you had a good experience with Bouligand et al. (2009) method. I'm not familiar with it, but I don't quite like Tanaka method for a number of reasons. That's why I was interested on fitting the full curve instead of splitting it into low and high frequencies approximations (which lead to a linear fitting obtaining the top and bottom of the slab).

Yes I have the same feeling. Tanaka's is a very qualitative method in the way it handles portions of the radial power spectrum and thus difficult to extract uncertainties in a meaningful way. In [this](https://www.solid-earth-discuss.net/se-2019-9/) recent paper I looked at how the choice of window size affects CPD uncertainty using `pycurious`. To summarise, uncertainty increases substantially with the thickness of the magnetised layer, but may be tempered with a larger window size.

Cool! I'll check out `tesina-fisica` soon. My Spanish is not very good, but I'll have a look around the code. Google Translate is getting pretty good these days... :wink:

**Comment by santisoler** [comment]
Congratulations on that paper! I'll share it among my coworkers!
You're right about the window size! On my Thesis I've made some quick analytical analysis about the minimum size of the window needed to catch the maximum of the radially averaged power spectrum located on the low frequencies.
Hope it can be useful for you.

Tell me if you struggle with the translation, I can help you a bit if you need to.
